/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MyMMLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMyMMLWebModule extends DefaultWebModule {

}
