/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Algo</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getAlgo()
 * @model
 * @generated
 */
public enum Algo implements Enumerator
{
  /**
   * The '<em><b>Decision Tree Classifier</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECISION_TREE_CLASSIFIER_VALUE
   * @generated
   * @ordered
   */
  DECISION_TREE_CLASSIFIER(0, "DecisionTreeClassifier", "DecisionTreeClassifier"),

  /**
   * The '<em><b>SVM</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVM_VALUE
   * @generated
   * @ordered
   */
  SVM(1, "SVM", "SVM"),

  /**
   * The '<em><b>J48</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #J48_VALUE
   * @generated
   * @ordered
   */
  J48(2, "J48", "J48"),

  /**
   * The '<em><b>Naive Bayes</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAIVE_BAYES_VALUE
   * @generated
   * @ordered
   */
  NAIVE_BAYES(3, "NaiveBayes", "NaiveBayes");

  /**
   * The '<em><b>Decision Tree Classifier</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DECISION_TREE_CLASSIFIER
   * @model name="DecisionTreeClassifier"
   * @generated
   * @ordered
   */
  public static final int DECISION_TREE_CLASSIFIER_VALUE = 0;

  /**
   * The '<em><b>SVM</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SVM
   * @model
   * @generated
   * @ordered
   */
  public static final int SVM_VALUE = 1;

  /**
   * The '<em><b>J48</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #J48
   * @model
   * @generated
   * @ordered
   */
  public static final int J48_VALUE = 2;

  /**
   * The '<em><b>Naive Bayes</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NAIVE_BAYES
   * @model name="NaiveBayes"
   * @generated
   * @ordered
   */
  public static final int NAIVE_BAYES_VALUE = 3;

  /**
   * An array of all the '<em><b>Algo</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Algo[] VALUES_ARRAY =
    new Algo[]
    {
      DECISION_TREE_CLASSIFIER,
      SVM,
      J48,
      NAIVE_BAYES,
    };

  /**
   * A public read-only list of all the '<em><b>Algo</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Algo> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Algo</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Algo get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Algo result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Algo</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Algo getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Algo result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Algo</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Algo get(int value)
  {
    switch (value)
    {
      case DECISION_TREE_CLASSIFIER_VALUE: return DECISION_TREE_CLASSIFIER;
      case SVM_VALUE: return SVM;
      case J48_VALUE: return J48;
      case NAIVE_BAYES_VALUE: return NAIVE_BAYES;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Algo(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Algo
