/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithm Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myMML.AlgorithmSet#getAlgoName <em>Algo Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getAlgorithmSet()
 * @model
 * @generated
 */
public interface AlgorithmSet extends Element
{
  /**
   * Returns the value of the '<em><b>Algo Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl1.myMML.Algo}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Algo Name</em>' attribute.
   * @see org.xtext.example.mydsl1.myMML.Algo
   * @see #setAlgoName(Algo)
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getAlgorithmSet_AlgoName()
   * @model
   * @generated
   */
  Algo getAlgoName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myMML.AlgorithmSet#getAlgoName <em>Algo Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Algo Name</em>' attribute.
   * @see org.xtext.example.mydsl1.myMML.Algo
   * @see #getAlgoName()
   * @generated
   */
  void setAlgoName(Algo value);

} // AlgorithmSet
