/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl1.myMML.MyMMLFactory
 * @model kind="package"
 * @generated
 */
public interface MyMMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myMML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl1/MyMML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myMML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyMMLPackage eINSTANCE = org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.MMLGeneratorImpl <em>MML Generator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.MMLGeneratorImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getMMLGenerator()
   * @generated
   */
  int MML_GENERATOR = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_GENERATOR__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>MML Generator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MML_GENERATOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.InstructionImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.PutInImpl <em>Put In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.PutInImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getPutIn()
   * @generated
   */
  int PUT_IN = 2;

  /**
   * The feature id for the '<em><b>Put Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_IN__PUT_ID = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_IN__VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Put In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUT_IN_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.ElementImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 3;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.FileSetImpl <em>File Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.FileSetImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getFileSet()
   * @generated
   */
  int FILE_SET = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_SET__TEXT = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>File Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILE_SET_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.PredictiveColumnsImpl <em>Predictive Columns</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.PredictiveColumnsImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getPredictiveColumns()
   * @generated
   */
  int PREDICTIVE_COLUMNS = 5;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVE_COLUMNS__COLUMN = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Predictive Columns</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICTIVE_COLUMNS_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.CibleColumnImpl <em>Cible Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.CibleColumnImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getCibleColumn()
   * @generated
   */
  int CIBLE_COLUMN = 6;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIBLE_COLUMN__COLUMN = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Cible Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CIBLE_COLUMN_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.TestValueSizeImpl <em>Test Value Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.TestValueSizeImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getTestValueSize()
   * @generated
   */
  int TEST_VALUE_SIZE = 7;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_VALUE_SIZE__SIZE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Test Value Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEST_VALUE_SIZE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.TrainValueSizeImpl <em>Train Value Size</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.TrainValueSizeImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getTrainValueSize()
   * @generated
   */
  int TRAIN_VALUE_SIZE = 8;

  /**
   * The feature id for the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAIN_VALUE_SIZE__SIZE = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Train Value Size</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAIN_VALUE_SIZE_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.impl.AlgorithmSetImpl <em>Algorithm Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.impl.AlgorithmSetImpl
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getAlgorithmSet()
   * @generated
   */
  int ALGORITHM_SET = 9;

  /**
   * The feature id for the '<em><b>Algo Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_SET__ALGO_NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Algorithm Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_SET_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl1.myMML.Algo <em>Algo</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl1.myMML.Algo
   * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getAlgo()
   * @generated
   */
  int ALGO = 10;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.MMLGenerator <em>MML Generator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>MML Generator</em>'.
   * @see org.xtext.example.mydsl1.myMML.MMLGenerator
   * @generated
   */
  EClass getMMLGenerator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl1.myMML.MMLGenerator#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.example.mydsl1.myMML.MMLGenerator#getInstructions()
   * @see #getMMLGenerator()
   * @generated
   */
  EReference getMMLGenerator_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl1.myMML.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.PutIn <em>Put In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Put In</em>'.
   * @see org.xtext.example.mydsl1.myMML.PutIn
   * @generated
   */
  EClass getPutIn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.PutIn#getPutId <em>Put Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Put Id</em>'.
   * @see org.xtext.example.mydsl1.myMML.PutIn#getPutId()
   * @see #getPutIn()
   * @generated
   */
  EAttribute getPutIn_PutId();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl1.myMML.PutIn#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl1.myMML.PutIn#getValue()
   * @see #getPutIn()
   * @generated
   */
  EReference getPutIn_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.xtext.example.mydsl1.myMML.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.FileSet <em>File Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>File Set</em>'.
   * @see org.xtext.example.mydsl1.myMML.FileSet
   * @generated
   */
  EClass getFileSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.FileSet#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.mydsl1.myMML.FileSet#getText()
   * @see #getFileSet()
   * @generated
   */
  EAttribute getFileSet_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.PredictiveColumns <em>Predictive Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predictive Columns</em>'.
   * @see org.xtext.example.mydsl1.myMML.PredictiveColumns
   * @generated
   */
  EClass getPredictiveColumns();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.PredictiveColumns#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see org.xtext.example.mydsl1.myMML.PredictiveColumns#getColumn()
   * @see #getPredictiveColumns()
   * @generated
   */
  EAttribute getPredictiveColumns_Column();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.CibleColumn <em>Cible Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cible Column</em>'.
   * @see org.xtext.example.mydsl1.myMML.CibleColumn
   * @generated
   */
  EClass getCibleColumn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.CibleColumn#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see org.xtext.example.mydsl1.myMML.CibleColumn#getColumn()
   * @see #getCibleColumn()
   * @generated
   */
  EAttribute getCibleColumn_Column();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.TestValueSize <em>Test Value Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Test Value Size</em>'.
   * @see org.xtext.example.mydsl1.myMML.TestValueSize
   * @generated
   */
  EClass getTestValueSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.TestValueSize#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.xtext.example.mydsl1.myMML.TestValueSize#getSize()
   * @see #getTestValueSize()
   * @generated
   */
  EAttribute getTestValueSize_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.TrainValueSize <em>Train Value Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Train Value Size</em>'.
   * @see org.xtext.example.mydsl1.myMML.TrainValueSize
   * @generated
   */
  EClass getTrainValueSize();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.TrainValueSize#getSize <em>Size</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Size</em>'.
   * @see org.xtext.example.mydsl1.myMML.TrainValueSize#getSize()
   * @see #getTrainValueSize()
   * @generated
   */
  EAttribute getTrainValueSize_Size();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl1.myMML.AlgorithmSet <em>Algorithm Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm Set</em>'.
   * @see org.xtext.example.mydsl1.myMML.AlgorithmSet
   * @generated
   */
  EClass getAlgorithmSet();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl1.myMML.AlgorithmSet#getAlgoName <em>Algo Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Algo Name</em>'.
   * @see org.xtext.example.mydsl1.myMML.AlgorithmSet#getAlgoName()
   * @see #getAlgorithmSet()
   * @generated
   */
  EAttribute getAlgorithmSet_AlgoName();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl1.myMML.Algo <em>Algo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Algo</em>'.
   * @see org.xtext.example.mydsl1.myMML.Algo
   * @generated
   */
  EEnum getAlgo();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyMMLFactory getMyMMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.MMLGeneratorImpl <em>MML Generator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.MMLGeneratorImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getMMLGenerator()
     * @generated
     */
    EClass MML_GENERATOR = eINSTANCE.getMMLGenerator();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MML_GENERATOR__INSTRUCTIONS = eINSTANCE.getMMLGenerator_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.InstructionImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.PutInImpl <em>Put In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.PutInImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getPutIn()
     * @generated
     */
    EClass PUT_IN = eINSTANCE.getPutIn();

    /**
     * The meta object literal for the '<em><b>Put Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUT_IN__PUT_ID = eINSTANCE.getPutIn_PutId();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PUT_IN__VALUE = eINSTANCE.getPutIn_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.ElementImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.FileSetImpl <em>File Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.FileSetImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getFileSet()
     * @generated
     */
    EClass FILE_SET = eINSTANCE.getFileSet();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILE_SET__TEXT = eINSTANCE.getFileSet_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.PredictiveColumnsImpl <em>Predictive Columns</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.PredictiveColumnsImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getPredictiveColumns()
     * @generated
     */
    EClass PREDICTIVE_COLUMNS = eINSTANCE.getPredictiveColumns();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREDICTIVE_COLUMNS__COLUMN = eINSTANCE.getPredictiveColumns_Column();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.CibleColumnImpl <em>Cible Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.CibleColumnImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getCibleColumn()
     * @generated
     */
    EClass CIBLE_COLUMN = eINSTANCE.getCibleColumn();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CIBLE_COLUMN__COLUMN = eINSTANCE.getCibleColumn_Column();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.TestValueSizeImpl <em>Test Value Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.TestValueSizeImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getTestValueSize()
     * @generated
     */
    EClass TEST_VALUE_SIZE = eINSTANCE.getTestValueSize();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEST_VALUE_SIZE__SIZE = eINSTANCE.getTestValueSize_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.TrainValueSizeImpl <em>Train Value Size</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.TrainValueSizeImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getTrainValueSize()
     * @generated
     */
    EClass TRAIN_VALUE_SIZE = eINSTANCE.getTrainValueSize();

    /**
     * The meta object literal for the '<em><b>Size</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAIN_VALUE_SIZE__SIZE = eINSTANCE.getTrainValueSize_Size();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.impl.AlgorithmSetImpl <em>Algorithm Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.impl.AlgorithmSetImpl
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getAlgorithmSet()
     * @generated
     */
    EClass ALGORITHM_SET = eINSTANCE.getAlgorithmSet();

    /**
     * The meta object literal for the '<em><b>Algo Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM_SET__ALGO_NAME = eINSTANCE.getAlgorithmSet_AlgoName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl1.myMML.Algo <em>Algo</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl1.myMML.Algo
     * @see org.xtext.example.mydsl1.myMML.impl.MyMMLPackageImpl#getAlgo()
     * @generated
     */
    EEnum ALGO = eINSTANCE.getAlgo();

  }

} //MyMMLPackage
