/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Put In</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myMML.PutIn#getPutId <em>Put Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl1.myMML.PutIn#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getPutIn()
 * @model
 * @generated
 */
public interface PutIn extends Instruction
{
  /**
   * Returns the value of the '<em><b>Put Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Put Id</em>' attribute.
   * @see #setPutId(String)
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getPutIn_PutId()
   * @model
   * @generated
   */
  String getPutId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myMML.PutIn#getPutId <em>Put Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Put Id</em>' attribute.
   * @see #getPutId()
   * @generated
   */
  void setPutId(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Element)
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getPutIn_Value()
   * @model containment="true"
   * @generated
   */
  Element getValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myMML.PutIn#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Element value);

} // PutIn
