/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Result Display Params Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myMML.ResultDisplayParamsSet#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getResultDisplayParamsSet()
 * @model
 * @generated
 */
public interface ResultDisplayParamsSet extends EObject
{
  /**
   * Returns the value of the '<em><b>Params</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.mydsl1.myMML.DisplayParams}.
   * The literals are from the enumeration {@link org.xtext.example.mydsl1.myMML.DisplayParams}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' attribute list.
   * @see org.xtext.example.mydsl1.myMML.DisplayParams
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getResultDisplayParamsSet_Params()
   * @model unique="false"
   * @generated
   */
  EList<DisplayParams> getParams();

} // ResultDisplayParamsSet
