/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Strategy Set</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myMML.StrategySet#getStrategy <em>Strategy</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getStrategySet()
 * @model
 * @generated
 */
public interface StrategySet extends EObject
{
  /**
   * Returns the value of the '<em><b>Strategy</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl1.myMML.Strategy}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Strategy</em>' attribute.
   * @see org.xtext.example.mydsl1.myMML.Strategy
   * @see #setStrategy(Strategy)
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getStrategySet_Strategy()
   * @model
   * @generated
   */
  Strategy getStrategy();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myMML.StrategySet#getStrategy <em>Strategy</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Strategy</em>' attribute.
   * @see org.xtext.example.mydsl1.myMML.Strategy
   * @see #getStrategy()
   * @generated
   */
  void setStrategy(Strategy value);

} // StrategySet
