/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.myMML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Test Value Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl1.myMML.TestValueSize#getSize <em>Size</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getTestValueSize()
 * @model
 * @generated
 */
public interface TestValueSize extends Element
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see org.xtext.example.mydsl1.myMML.MyMMLPackage#getTestValueSize_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl1.myMML.TestValueSize#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

} // TestValueSize
