/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1;

import org.xtext.example.mydsl1.AbstractMyMMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyMMLRuntimeModule extends AbstractMyMMLRuntimeModule {
}
