/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class MyMMLWebModule extends AbstractMyMMLWebModule {
}
