/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.web;

import org.xtext.example.mydsl1.web.AbstractMyMMLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MyMMLWebModule extends AbstractMyMMLWebModule {
}
