/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.myMML.ui.internal.MyMMLActivator;

public class MyMMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MyMMLActivator.getInstance().getInjector("org.xtext.example.mydsl1.MyMML");
	}

}
