/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl1.ide;

import org.xtext.example.mydsl1.ide.AbstractMyMMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyMMLIdeModule extends AbstractMyMMLIdeModule {
}
